Suffrage/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', include('pages.urls')),
	path('campaigns/', include('campaigns.urls')),
    path('users/',include('users.urls')),
	path('admin/', admin.site.urls),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/urls.py
from django.urls import path
from . import views

app_name = 'campaigns'
urlpatterns = [
	path('', views.index, name ='index'),
	path('<int:campaign_id>/', views.detail, name ='detail'),
	path('<int:campaign_id>/results/', views.results, name ='results'),
	path('<int:campaign_id>/vote/', views.vote, name ='vote'),
]

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
	path('', views.index, name ='index'),
]

campaigns/models.py
from django.db import models

from users.models import CustomUser
 
# Create your models here.
 
class Campaign(models.Model):
    organization_name = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')
 
    def __str__(self):
        return self.organization_name
 
 
class Candidates(models.Model):
    organization_name = models.ForeignKey(Campaign, on_delete = models.CASCADE)
    candidate_list = models.CharField(max_length = 200)
    votes = models.IntegerField(default=0)

 
    def __str__(self):
        return self.candidate_list
    
    class meta:
        verbose_name = "Candidate"

campaigns/views.py
from django.http.response import Http404, HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages



from .models import Campaign, Candidates

# Get questions and display them


def index(request):
	latest_candidate_list = Campaign.objects.order_by('-pub_date')[:5]
	context = {'latest_candidate_list': latest_candidate_list,}
	return render(request, 'campaigns/index.html', context)

# Show specific question and choices


def detail(request, campaign_id):
	campaign = Campaign.objects.get(pk = campaign_id)
	with open("new_data.txt","r") as rn:
		data = rn.read()
		if str(campaign.id) + ',' + str(request.user.username) in data:
			messages.warning(request,"you have already attended the poll.")
			return redirect(reverse("campaigns:index"))

	try:
		campaign = Campaign.objects.get(pk = campaign_id)
		with open('new_data.txt','a') as n:
			cid = str(campaign.id) + ','
			user = request.user.username
			n.writelines([cid,user])
			n.close
	except Campaign.DoesNotExist:
		raise Http404("Campaign does not exist")
	return render(request, 'campaigns/detail.html', {'campaign': campaign})

# Get question and display results


def results(request, campaign_id):
    campaign = get_object_or_404(Campaign, pk = campaign_id)
    return render(request, 'campaigns/results.html', {'campaign': campaign})

# Vote for a question choice

@login_required
def vote(request, campaign_id):
	
	
	# print(request.POST['choice'])
	campaign = get_object_or_404(Campaign, pk = campaign_id)

	# with open("Attendies-List.txt","r") as check:
	# 	lst = check.read()
	# 	data = str(campaign.organization_name)+','+str(request.user.username)
	# 	print(data)
	# 	if data in lst:
	# 		return(HttpResponse("You have already attended the pole"))

	
	try:
		selected_choice = campaign.candidates_set.get(pk = request.POST['choice'])
	except (KeyError, Candidates.DoesNotExist):
		# Redisplay the question voting form.
		return render(request, 'campaigns/detail.html', {
			'campaign': campaign,
			'error_message': "You didn't select a choice.",
		})
	else:

		selected_choice.votes += 1
		selected_choice.save()
		# with open("Attendies-List.txt",'a') as a:
		# 	name = str(campaign.organization_name) + ','
		# 	user = str(request.user.username)
		# 	a.writelines([name,user])
		# 	a.write('\n')
		# 	a.close()
	
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('campaigns:results', args =(campaign.id,)))

templates/campaigns/detail.html
{% extends 'base.html' %}
{% block content %}
<a class ="btn btn-secondary btn-sm mb-3" href ="{% url 'campaigns:index' %}"><b>Back To Campaigns</b></a>
<h1 class ="text-center mb-3">Campaign Name: {{ campaign.organization_name }}</h1>

{% if error_message %}
<p class ="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>

{% endif %}

<form action ="{% url 'campaigns:vote' campaign.id %}" method ="post">
	{% csrf_token %}
	{% for candidate in campaign.candidates_set.all %}
	<div class="card">
  <div class="card-header">
    <p><b>Candidate {{ forloop.counter }}</b></p>

  </div>
  <div class="card-body">
    <h5 class="card-title">Name: <b>{{ candidate.candidate_list }}</b></h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
	
    <button type ="submit"  name = "choice" id ="choice{{ forloop.counter }}"  value ="{{ candidate.id }}" class ="btn btn-success btn-lg btn-block mt-4"><b>Vote now</b></button>
  </div>
</div>
<br>

{% endfor %}
  
	{% comment %} {% for candidate in campaign.candidates_set.all %}
	<div class ="form-check">
		<input ty%pe ="radio" name ="choice" class ="form-check-input" id ="choice{{ forloop.counter }}"
			value ="{{ candidate.id }}" />
		<label for ="choice{{ forloop.counter }}">{{ candidate.candidate_list }}</label>
	</div>
	{% endfor %}
	<input type ="submit" value ="Vote" class ="btn btn-success btn-lg btn-block mt-4" /> {% endcomment %}
</form>
{% endblock %}

templates/campaigns/index.html
{% extends 'base.html' %}
{% block content %}
<h2 class ="text-center mb-3" style="border: 2px solid black; border-radius: 2px; padding: 5px;">Campaigns Available.</h2>
<div class="alert alert-primary" role="alert">
<p><b>Note: Once you have opened the poll you can't attend that poll again..</b></p>
</div>
{% if latest_candidate_list %}
{% for campaign in latest_candidate_list %}

<div class = "content-section">
<div class ="card-mb-3">
	<div class ="card-body">
		<p>Campaign name: <b>{{ campaign.organization_name }}</b></p>
		<b>Published On: {{ campaign.pub_date }}</b><br><br>
		
		<a href ="{% url 'campaigns:detail' campaign.id %}" class ="btn btn-primary btn-sm"><b>Cast your vote</b></a>
		{% comment %} <a href ="{% url 'campaigns:results' campaign.id %}" class ="btn btn-secondary btn-sm">Results</a> {% endcomment %}
	</div>
</div>
</div>
{% endfor %}
{% else %}

<p>No Campaigns available</p>

{% endif %}
{% endblock %}

templates/campaigns/results.html
{% extends 'base.html' %}
{% block content %}

<h1 class ="mb-3 text-center">Thank You for casting your vote</h1>
<center>
<img src="https://i.pinimg.com/originals/7b/dd/1b/7bdd1bc7db7fd48025d4e39a0e2f0fd8.jpg" height="200px" width="200px">

{% comment %} 
<ul class ="list-group mb-5">
	{% for candidate in campaign.choice_set.all %}
	<li class ="list-group-item">
		{{ candidates.candidate_list }} <span class ="badge badge-success float-right">{{ candidate.votes }}
			vote{{ candiate.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul> {% endcomment %}
<p><b>You have casted your vote successfully.</b></p>
<a class ="btn btn-secondary" href ="{% url 'campaigns:index' %}"><b>Back To Campaigns</b></a>
</center>
{% comment %} <a class ="btn btn-dark" href ="{% url 'campaigns:detail' campaign.id %}">Vote again?</a> {% endcomment %}
{% endblock %}